import type { Metadata } from "next";
import { AnimatePresence } from "framer-motion";
import { Space_Grotesk } from '@next/font/google';
import "./globals.css";
import NavBar from "./components/Navbar";

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Add font weights you want to use
  variable: '--font-space-grotesk', // Optional: Use for CSS variables
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} font-sans`}
      >
        <AnimatePresence mode="wait">
          <NavBar />
          
          {children}
        </AnimatePresence>
        
      </body>
    </html>
  );
}
